import { USER_WITH_MULTIPLE_SUBSCRIPTION, USER_WITH_ONE_SUBSCRIPTION, USER_WITHOUT_SUBSCRIPTION } from '@/mocks/users';

export const USER_TYPES = {
  DEFAULT_USER: 'default-user',
  USER_ONE_SUBSCRIPTION: 'user-one-subscription',
  USER_MULTIPLE_SUBSCRIPTION: 'user-multiple-subscription',
} as const;

export const userConfigs = {
  [USER_TYPES.DEFAULT_USER]: USER_WITHOUT_SUBSCRIPTION,
  [USER_TYPES.USER_ONE_SUBSCRIPTION]: USER_WITH_ONE_SUBSCRIPTION,
  [USER_TYPES.USER_MULTIPLE_SUBSCRIPTION]: USER_WITH_MULTIPLE_SUBSCRIPTION,
};
