import type { Metadata } from 'next';

import '../globals.css';

import { Source_Sans_3, Merriweather } from 'next/font/google';

import { Button } from '@/components/atoms';
import { USER_TYPES } from '@/constants/common';

const meriweatherFont = Merriweather({
  variable: '--font-meriweather',
  subsets: ['latin'],
});

const sourceSansProFont = Source_Sans_3({
  variable: '--font-source-sans-pro',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Newsletter',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`
          ${meriweatherFont.variable}
          ${sourceSansProFont.variable}
          antialiased
        `}
      >
        <div
          className={`
            relative mx-5 mt-3 mb-15 flex flex-col justify-center gap-3
            sm:flex-row
          `}
        >
          {Object.values(USER_TYPES).map((userType) => (
            <Button asChild key={userType}>
              <a href={`/connect/${userType}`}>{userType}</a>
            </Button>
          ))}
        </div>
        <div className="mx-auto h-px w-full max-w-layout bg-neutral-low-contrast" />
        <div
          className={`
            mx-0 my-15 max-w-layout
            sm:mx-5
            lg:mx-auto
          `}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
